---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media
  namespace: media
spec:
  volumeName: media
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: openebs-zfspv-pool
