---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    serviceMonitor:
      enabled: true
    config:
      storage_config:
        aws:
          bucketnames: loki
          endpoint: minio.minio:9000
          access_key_id: "${MINIO_USER_ACCESS_KEY}"
          secret_access_key: "${MINIO_USER_SECRET_KEY}"
          s3forcepathstyle: true
          insecure: true
        boltdb_shipper:
          active_index_directory: /data/loki/index
          cache_location: /data/loki/index_cache
          cache_ttl: 168h
          resync_interval: 5s
          shared_store: s3
        filesystem:
          directory: /data/loki/chunks
      compactor:
        working_directory: /data/loki/compactor
        shared_store: s3
