---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jr0dd-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://jr0dd.github.io/charts/
  timeout: 3m
