apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token
    namespace: networking
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:NfBq4+i3Fw41Pv8EbsvUIdPYwAMUWfjlebXnc3PbwDcd2BGTouxCEA==,iv:5hMWZMzcVn1BC51X1SfG0cOK/MF32/go3RHMGESsgs0=,tag:UvGwQafgjLHeHJnu1UqLNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-21T04:18:58Z"
    mac: ENC[AES256_GCM,data:ZIPpiiGO8Ko9AW++rCzwr+/U6LgAONGCE1w0G0Q1kjommyjm2TuYCy+W5d/qlVZWIKENv26HaeBNBEXJHGN2bSmssMQPkZi5LTH+2fBr+6+H7mgcmqyddCLx92Viz+ReMxp0Xlc4JKnFk1iTlh29KNgCb54YEQMgjofLm8bAbgE=,iv:xAQHUHyIjeSacBCJFfs+3EWaDO2YYb1Sj1dtmBSIvSw=,tag:saAWMYefEDP4w3FNSnaDoQ==,type:str]
    pgp:
        - created_at: "2021-08-21T04:18:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAy/lHiZ0ctOOARAAtVl8nh5qRiAFafXqihKlCuK1Ifkz4xy0WPdENJBxzNF4
            6Xzq3ZfUxtl596yuKOKHbrOZKWeLDap7lmPy7pQln99WgAbvhVCLt++vFbgiNBek
            TUVc6vMjVvqZRCG8TIi931Patey7mZZ1hid5eOVpjkLjOpAfMSoXAg1HSDZA6zzu
            gbGgKh2yN34SGz68wbMLQ3w1AS6qyYCO/hvoZnTq61RJZPKOe9b7tPLXudBax7e3
            whiV8cBeP+RRXddBm2KobxYr/6BDF/Jgv5e1iNRYy6xrnpk7JZG7ik1+qlG4dA1L
            ihuj6Nl/gmVIPARPvAEEbBP9PT5A5oUw0DQId8Pr2lT79V8oNxEgqNsIa/ZSogKl
            TWnGNz542pvz7GHpyWduHaAuHdHYg3d0ptwRDve0zjMKwfHIceWIo2QW9ai/gPob
            VT0/XBezPuaga2fGzOh3fm1hz06Grj9m1P7IonnKfBgjhSS49BSz4TanygJvp4tJ
            r1VfFg4sl+6BV14wh+0VU/U5zwC48Wpo7nXJ1J+kJCyTkYSkKXXPHl9IBPia4Dhi
            DPIjZ0T+atU10ouDa72K/5QU2MocORhaA9FkKZBQ+a/knrlldySnZ+ZF5Udmv45X
            rNsumEfNcpRSK54wWPGF4uEqzzmE6Fm2KsbPxQ1KRxo7tyXydjPQkFXGI3MHvmfS
            XgGNdi1rhhuZfzYce6FOxqvLq02FoK++os4seS8ux8LSo7WeZj4QBMaZfRuBBgoC
            u9BsCU9JAcElx8RDmS8GkDxv+fOnlDt6dyf2dH+N6LY6TeD3Rb+LXfeEytcLrIc=
            =rKO3
            -----END PGP MESSAGE-----
          fp: 90D70EF82A524A486F33D8EF787289B5A6C8ED92
        - created_at: "2021-08-21T04:18:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0eH6NQLJXdcAQ/+Jj28MWKCWO536pf8y5hkfDJmi14NZkbkP98LUH2dEfZa
            SpgEF2+0kGgmqrR2tS4lJ6qvXJRk2cB+rNGaDouem0FeSrRnlIKSTwVIQVwVxGnh
            Er1T7BDtoosYDYRRKT9JIJ/xFOvRBhFtYaZqnnO+HqYRCbnBQ0SeQBaBgmcTcDG3
            8IQ6AJrPt346Znzyq40qC500JYJiJlq5V75/r7DpnzKlv1EtEGS3+G8TFiwmRUxL
            SLY4xE4sYQib2zTtZyvCvzyId4cNR/jgHgrFswSNtOwmeir3r2UY3gSghekrgLcQ
            0APT8ECtzLWTBuHiQrQui7mr6SNlvEJkY4juW2WnwqnNmqRti3TejWIXYCQC8c5p
            zJKLZ9AHezLMamw/yuvNHFyBtlF9fr5eaPLhc1X79QneEYwe9MdlsFvL7eXKmeaM
            HiaFYJTAIMCgsv8rYYDwJgKXqPk6V1txQRS27q6L1vFmdpznhSF4Zh93+eusU5SV
            oJW3rhgOdEH/fbya+Ey3v/LqGn/qPaHUMFKhc2vls2W1BN3zYgO6Q3NDHUGoPYCB
            Qyb6QYmwCooIE5SyGgE9LuKS+b6WZpd69ewS38oPSO+rbtdJhrv7k/YXUS2ZbX7Q
            GST3miz8DM/9C5nrrFOtZkPNQyJMQxRQplGl1DEziJW33lTx6UfCT188pQzpZjzS
            XgF3+Ow32/qyMVYMCT9iox7ed7n+WyDqG0hsA30RlJbtrvYzf6ttzhne23ZiGrdv
            xFFbHd9MbSXFJcjYG2NoWEDnMXcz2bsRGdZXhLc1C3PD9ftXR5JRZ8XtwKUBeA4=
            =2Yk/
            -----END PGP MESSAGE-----
          fp: AFE6721008A3DA5B6A027947B8C7431C430C6D24
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
