---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://ori-edge.github.io/k8s_gateway/
      chart: k8s-gateway
      version: 1.0.10
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway-charts
        namespace: flux-system
      interval: 5m
  values:
    nameOverride: k8s-gateway
    domain: "${SECRET_DOMAIN}"
    ttl: 1
    service:
      type: LoadBalancer
      port: 53
      externalTrafficPolicy: Local
      loadBalancerIP: ${LB_K8S_GATEWAY_IP}
