---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: overseerr-config-v1
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: openebs-zfspv-pool
