---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prowlarr-config-v1
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-zfspv-pool
