---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: prowlarr
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/prowlarr
      tag: v0.1.1.953
    controller:
      enabled: true
      replicas: 1
      strategy: RollingUpdate
    env:
      TZ: "America/New_York"
    service:
      main:
        ports:
          http:
            port: 9696
    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config-v1
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: networking-internal-auth@kubernetescrd
        hosts:
          - host: "prowlarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: prowlarr-tls
            hosts:
              - "prowlarr.${SECRET_DOMAIN}"
