---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-config-v1
  namespace: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: openebs-zfspv-pool
