---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: discord-stock-ticker
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://jr0dd.github.io/charts/
      chart: discord-stock-ticker
      version: 13.0.0
      sourceRef:
        kind: HelmRepository
        name: jr0dd-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/jr0dd/discord-stock-ticker
      tag: v3.5.1
    controller:
      enabled: true
      replicas: 1
      strategy: RollingUpdate
    env:
      TZ: "America/New_York"
    envFrom:
      - secretRef:
          name: discord-tokens
    persistence:
      config:
        enabled: true
        type: custom
        mountPath: /app/payload.sh
        subPath: payload.sh
        readOnly: true
        volumeSpec:
          configMap:
            name: payload
            defaultMode: 0755
    metrics:
      enabled: true
      prometheusRule:
        enabled: true
    configmap:
      enabled: false
    podAnnotations:
      configmap.reloader.stakater.com/reload: "payload"
