---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-config-v1
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: openebs-zfspv-ssd
