---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.10.2
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
      interval: 5m
  values:
    configInline:
      peers:
        - peer-address: "${GATEWAY_IP}"
          peer-asn: 64550
          my-asn: 64512
      address-pools:
        - name: mikrotik
          protocol: bgp
          avoid-buggy-ips: true
          addresses:
            - "${METALLB_POOL}"
    prometheus:
      scrapeAnnotations: false
      metricsPort: 7472
      podMonitor:
        enabled: true
        relabelings:
          - sourceLabels: ['namespace', 'job']
            regex: ".+/(.*)"
            targetLabel: "job"
            replacement: "$1"
      prometheusRule:
        enabled: true
        # MetalLBStaleConfig
        staleConfig:
          enabled: true
          labels:
            severity: warning
        # MetalLBConfigNotLoaded
        configNotLoaded:
          enabled: true
          labels:
            severity: warning
        # MetalLBAddressPoolExhausted
        addressPoolExhausted:
          enabled: true
          labels:
            severity: critical
        # MetalLBAddressPoolUsage
        addressPoolUsage:
          enabled: true
          thresholds:
            - percent: 75
              labels:
                severity: warning
            - percent: 85
              labels:
                severity: warning
            - percent: 95
              labels:
                severity: critical
        # MetalLBBGPSessionDown
        bgpSessionDown:
          enabled: true
          labels:
            severity: critical
