---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: openebs-zfs-localpv-source
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/openebs/zfs-localpv.git
  ref:
    # renovate: registryUrl=https://openebs.github.io/zfs-localpv
    tag: zfs-localpv-1.9.8
  ignore: |
    # exclude all
    /*
    # include deploy crds dir
    !/deploy/helm/charts/crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: openebs-zfs-localpv-crds
  namespace: flux-system
spec:
  interval: 15m
  prune: false
  sourceRef:
    kind: GitRepository
    name: openebs-zfs-localpv-source
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: volumesnapshotclasses.snapshot.storage.k8s.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: volumesnapshotcontents.snapshot.storage.k8s.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: volumesnapshots.snapshot.storage.k8s.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: zfsbackups.zfs.openebs.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: zfsnodes.zfs.openebs.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: zfsrestores.zfs.openebs.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: zfssnapshots.zfs.openebs.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: zfsvolumes.zfs.openebs.io
