---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zfs-localpv
  namespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://openebs.github.io/zfs-localpv
      chart: zfs-localpv
      version: 1.9.8
      sourceRef:
        kind: HelmRepository
        name: openebs-zfs-localpv-charts
        namespace: flux-system
      interval: 5m
  values:
    release:
      version: 1.9.3
    zfsNode:
      kubeletDir: "/var/lib/kubelet/"
    zfsPlugin:
      image:
        registry: quay.io/
        repository: openebs/zfs-driver
        pullPolicy: IfNotPresent
        tag: 1.9.3
    crd:
      enableInstall: false
