---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}"
  namespace: networking
spec:
  secretName: "${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
